In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# import dataset #
dataset = pd.read_csv('stunting_dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['Male' 17 3.0 ... 10.0 72.2 'No']
 ['Female' 11 2.9 ... 2.9 65.0 'No']
 ['Male' 16 2.9 ... 8.5 72.2 'No']
 ...
 ['Male' 16 2.8 ... 7.7 49.0 'No']
 ['Male' 14 2.8 ... 10.0 69.0 'No']
 ['Female' 10 3.0 ... 7.7 80.0 'No']]


In [6]:
print(y)

['No' 'Yes' 'Yes' ... 'No' 'Yes' 'Yes']


In [7]:
# menghilangkan missing value #
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [8]:
print(x)

[['Male' 17.0 3.0 ... 10.0 72.2 'No']
 ['Female' 11.0 2.9 ... 2.9 65.0 'No']
 ['Male' 16.0 2.9 ... 8.5 72.2 'No']
 ...
 ['Male' 16.0 2.8 ... 7.7 49.0 'No']
 ['Male' 14.0 2.8 ... 10.0 69.0 'No']
 ['Female' 10.0 3.0 ... 7.7 80.0 'No']]


In [9]:
# encoding data Atribute #
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[0.0 1.0 17.0 ... 10.0 72.2 'No']
 [1.0 0.0 11.0 ... 2.9 65.0 'No']
 [0.0 1.0 16.0 ... 8.5 72.2 'No']
 ...
 [0.0 1.0 16.0 ... 7.7 49.0 'No']
 [0.0 1.0 14.0 ... 10.0 69.0 'No']
 [1.0 0.0 10.0 ... 7.7 80.0 'No']]


In [11]:
# encoding data class/label #
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 1 1 ... 0 1 1]


In [13]:
# membagi dataset (training & test) #
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [14]:
print(x_train)

[[0.0 1.0 14.0 ... 7.1 73.5 'No']
 [1.0 0.0 10.0 ... 8.4 68.3 'No']
 [0.0 1.0 11.0 ... 7.7 68.3 'No']
 ...
 [0.0 1.0 17.0 ... 6.4 69.0 'No']
 [0.0 1.0 13.0 ... 9.0 69.0 'No']
 [0.0 1.0 14.0 ... 7.1 49.0 'No']]


In [15]:
print(x_test)

[[1.0 0.0 7.0 ... 7.7 72.2 'No']
 [0.0 1.0 12.0 ... 8.4 49.0 'No']
 [0.0 1.0 11.0 ... 2.9 71.0 'No']
 ...
 [0.0 1.0 25.0 ... 7.0 65.0 'No']
 [1.0 0.0 14.0 ... 7.0 65.0 'No']
 [1.0 0.0 15.0 ... 7.0 63.0 'No']]


In [16]:
print(y_train)

[1 0 0 ... 1 1 0]


In [17]:
print(y_test)

[1 1 1 ... 1 0 1]


In [25]:
#Feature Scaling#
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, :3] = sc.fit_transform(x_train[:, :3])
x_test[:, :3] = sc.transform(x_test[:, :3])

In [26]:
print(x_train)

[[-0.7762500258061397 0.7762500258061397 -0.02631904478431329 ... 7.1
  73.5 'No']
 [1.2882447236782744 -1.2882447236782744 -0.5348996203265973 ... 8.4 68.3
  'No']
 [-0.7762500258061397 0.7762500258061397 -0.4077544764410263 ... 7.7 68.3
  'No']
 ...
 [-0.7762500258061397 0.7762500258061397 0.3551163868723997 ... 6.4 69.0
  'No']
 [-0.7762500258061397 0.7762500258061397 -0.1534641886698843 ... 9.0 69.0
  'No']
 [-0.7762500258061397 0.7762500258061397 -0.02631904478431329 ... 7.1
  49.0 'No']]


In [27]:
print(x_test)

[[1.2882447236782744 -1.2882447236782744 -0.9163350519833103 ... 7.7 72.2
  'No']
 [-0.7762500258061397 0.7762500258061397 -0.2806093325554553 ... 8.4 49.0
  'No']
 [-0.7762500258061397 0.7762500258061397 -0.4077544764410263 ... 2.9 71.0
  'No']
 ...
 [-0.7762500258061397 0.7762500258061397 1.3722775379569678 ... 7.0 65.0
  'No']
 [1.2882447236782744 -1.2882447236782744 -0.02631904478431329 ... 7.0
  65.0 'No']
 [1.2882447236782744 -1.2882447236782744 0.10082609910125771 ... 7.0 63.0
  'No']]
